# Generated by Django 3.2.3 on 2021-08-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anherc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymant',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
