# Generated by Django 3.2.3 on 2021-08-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anherc', '0002_alter_paymant_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycurse',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='curse',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='enrolllistener',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='paymant',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='typepaymant',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
